OPENAI_API_KEY = "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"  # paste your real key here
